### ISSUE TITLE
sna4onnx: about the param --connection_dest_op_input_names

### ISSUE THREAD

**Issue by cccccccyj** [PINTO0309/simple-onnx-processing-tools#1]
>   --connection_dest_op_input_names ADDOP_NAME ADDOP_OUTPUT_NAME DESTOP_NAME DESTOP_INPUT_NAME
      Specify the name of the input name from which to connect.
      e.g.
      -Before-
        [OpA]oname1 - iname1[OpB]oname1
        [OpC]oname1

      -After-
        [OpA]oname1 - iname1[AddOP1]oname1 - iname1[OpB]oname1
        [OpC]oname1 - iname2[AddOP1]

      When extrapolating a new OP between OpA and OpB.
      --connection_dest_op_input_names AddOP1 oname1 OpB iname1

When I want to add a new OP after [Opc]onname1，how should this parameter be set?
That is to say, if I want to add a new node after the "output" node, how should this parameter be set?

**Comment by PINTO0309** [comment]
Sample of adding `Abs [AddOP1]` between `OpC` and `SomeOP`.
```
[OpC] oname1(float32) - iname2(float32) [AddOP1] oname3(float32) - iname4(float32) [SomeOP] oname5(float32)
```
```bash
$ sna4onnx \
--input_onnx_file_path xxx.onnx \
--connection_src_op_output_name OpC oname1 AddOP1 iname2 \
--connection_dest_op_input_name AddOP1 oname3 SomeOP iname4 \
--add_op_type Abs \
--add_op_name AddOP1 \
--add_op_input_variables iname2 float32 [x,x,x] \
--add_op_output_variables oname3 float32 [x,x,x] \
--output_onnx_file_path yyy.onnx
```

**Comment by PINTO0309** [comment]
To add at the end of the model.

1. Generate `Abs` OP.
    ```bash
    $ sog4onnx \
    --op_type Abs \
    --opset 11 \
    --op_name AddOP1 \
    --input_variables iname2 float32 [1,1] \
    --output_variables oname3 float32 [1,1]
    ```
    ![image](https://user-images.githubusercontent.com/33194443/167132034-7873032f-f1d8-4b02-a604-373ec22e58cb.png)
    ![image](https://user-images.githubusercontent.com/33194443/167133076-6f4328a0-ada7-4c32-8d21-ed37fea30dde.png)
    ![image](https://user-images.githubusercontent.com/33194443/167133136-b6013f67-7854-4ff6-b366-1fee108ff6e5.png)

2. The generated `Abs` OP is merged with the model from which it was extended.
![image](https://user-images.githubusercontent.com/33194443/167133285-361a839d-3273-47e1-a940-7989801fae93.png)
![image](https://user-images.githubusercontent.com/33194443/167132735-7a6f1c1c-5636-4eca-b3ed-3415875f7d0f.png)
    ```bash
    $ snc4onnx \
    --input_onnx_file_paths aaa.onnx Abs.onnx \
    --srcop_destop Identity iname2 \
    --op_prefixes_after_merging aaa bbb

    or

    $ snc4onnx \
    --input_onnx_file_paths aaa.onnx Abs.onnx \
    --srcop_destop Identity iname2
    ```
3. Results
    ![image](https://user-images.githubusercontent.com/33194443/167133452-03b9be21-6a44-4adc-ab45-10eb803a4572.png)
    ![image](https://user-images.githubusercontent.com/33194443/167133684-8915ee5e-cb19-4388-8c25-cc58fae753fd.png)
    ![image](https://user-images.githubusercontent.com/33194443/167133767-486c6de9-59dd-48de-9f9a-65182cf29a7b.png)
