### ISSUE TITLE
Convert input and output to NCHW format

### ISSUE THREAD

**Issue by kaleab-k** [PINTO0309/simple-onnx-processing-tools#3]
Hi @PINTO0309,

Thanks for the great tools. 

I tried to use [scc4onnx](https://github.com/PINTO0309/scc4onnx) to change the input and output shape from NHWC to NCHW of this ONNX [file](https://github.com/PINTO0309/PINTO_model_zoo/files/9330624/model_float32.onnx.zip). 

However, I was only able to change the input shape and not the output shape. I was wondering if you can help me change both input and output nodes shape to be in NCHW format. 

Thank you!

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/snd4onnx
```bash
snd4onnx \
--remove_node_names Transpose__478 \
--input_onnx_file_path model_float32.onnx \
--output_onnx_file_path model_float32_.onnx
```
![image](https://user-images.githubusercontent.com/33194443/185370053-4984b1d3-2b1e-4327-886a-9ab33239ae47.png)

**Comment by kaleab-k** [comment]
Hi @PINTO0309, 
Thank you! But, this results in a corrupted output (black image).
Is it possible to generate the model in NCHW format?
