### ISSUE TITLE
How about input with batch size > 1

### ISSUE THREAD

**Issue by thangphung215** [PINTO0309/simple-onnx-processing-tools#6]
### Issue Type

Feature Request

### Model Name

model1 4x3x256x256
model2 4x3x256x256

### ONNX URL

model1.onnx
model2.onnx

### Description

combine 2 model with batch size > 1

### Relevant Log Output

None

### URL or source code for simple inference testing code

None

**Comment by PINTO0309** [comment]
I don't understand.

**Comment by thangphung215** [comment]
As your example it is use with batchsize=1, but in my application, I need more than 1, batchsize=4 but when using your tool, it always turn input shape to batch size 1 and I want to ask about merging with batchsize=4. 
Thank you very much for your support
