### ISSUE TITLE
Convert model from ONNX QDQ Format to QOperator format or full-integer quantized TFLITE format.

### ISSUE THREAD

**Issue by hoangtv2000** [PINTO0309/simple-onnx-processing-tools#7]
### Issue Type

Feature Request

### Model Name

resnet18.onnx

### ONNX URL

not provided

### Description

Hi @PINTO0309 
I am making a quantization flow that can perform QAT on torch model and convert it to Full-integer Format, that mean weight/bias/input/output tensor must be fixed-pointed integers.
I am looking for a quantization method by torch.fx and I obtained the model below. In order to perform full-integer quantization I have to convert this pattern below to QLinearConv or tflite model with disabled Quantize, Dequantize nodes removed. Can you suggest me any tool or method to do this.
Thank you.

![image](https://github.com/PINTO0309/simple-onnx-processing-tools/assets/58163069/b693cca3-ad6a-41f7-b82a-db3dd24d2506)

### Relevant Log Output

not provided

### URL or source code for simple inference testing code

not provided

**Comment by PINTO0309** [comment]
https://github.com/google-ai-edge/ai-edge-torch

https://github.com/AlexanderLutsenko/nobuco

https://github.com/alibaba/TinyNeuralNetwork
